what is polynomial feature ? 

what is vectorization in numpy ?

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [6]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset.head(10)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

Data Preprocessing 

All the steps that are involved in preparing the data to built a machine learning model is called data preprocessing. 

It involves taking care of missing values, handling categorical values, scaling / normalization, etc..

In [7]:
dataset.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [8]:
#Seperate the User ID

#Method - 1
#x = dataset.drop(['User ID'], axis=1)
#y = dataset['User ID']
#print(x)
#print(y)

#Method - 2
print(dataset)
user_id = dataset['User ID']
print(user_id)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]
0      15624510
1      15810944
2      15668575
3      15603246
4      15804002
         ...
395    15691863
396    15706071
397    15654296
398    15755018
399    15594041
Name: User ID, Length: 400, dtype: int64

Assignment: Corelational relationship and co-variance realtionship

In [9]:
#Check for null value
dataset.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [10]:
predictor = dataset[['Age', 'EstimatedSalary']]
target = dataset['Purchased']

print(predictor)
print(target)

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]
0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [11]:
x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, 4].values

In [12]:
#Splitting the dataset into Training set and Test set
#train test - split (75 - 25)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [13]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
print(x_train[0:5])

[[ 2.0052225   0.72479792]
 [-1.22740379 -1.43119212]
 [ 0.33993017 -0.33843005]
 [-0.93352867  0.54759326]
 [ 0.43788855  0.28178627]]

In [15]:
#Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [16]:
#To find out and write everything about the output of logisitic regression
#Predecting the Test set results
y_pred = classifier.predict(x_test)

#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
re = recall_score(y_test, y_pred)

print(cm)
print("\n", ac*100)
print("\n", f1*100)
print("\n", re*100)

[[79  1]
 [20 32]]

 84.0909090909091

 75.29411764705883

 61.53846153846154